stages:
  - build
  - deploy

build-ui:
  stage: build
  before_script:
    - echo "Before ui build script"
    - echo $PWD
    - ls
  script:
    - cd ui
    - echo "-----Building UI-----"
    - docker build -t lecture13-smoothie-stand-ui .

build-server:
  stage: build
  before_script:
    - echo "Before server build script"
    - echo $PWD
    - ls
  script:
    - cd server
    - echo "-----Building Server-----"
    - docker build -t lecture13-smoothie-stand-server .

deploy:
  stage: deploy
  script:
    - kubectl delete -f k8s/
    - kubectl create -f k8s/