apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - image: numscore-server
        name: server
        imagePullPolicy: Never
        ports:
        - containerPort: 8131
          name: server
        env:
        - name: MONGO_URL
          value: mongodb://db
        - name: EXTERNAL_PORT
          value: "31000"
        - name: DISABLE_SECURITY
          value: foo-bar-baz